### ISSUE TITLE
count returned from surgery list does not match the number from creating chart

### ISSUE THREAD

**Issue by angelicalin** [visdesignlab/bloodvis#87]
e.g. CABG returns 2382, but the chart contains 822 when applying this CABG filter.

**Comment by JackWilb** [comment]
Is this not fixed on master?

**Comment by angelicalin** [comment]
nope

**Comment by JackWilb** [comment]
Which endpoints are you using to calculate both counts? I'll look into it again

**Comment by angelicalin** [comment]
`request_transfused_units`, `get_attributes`
